ตุงตุง
mookob4ever
ไม่อยู่

ตุงตุง เริ่มการโทรเป็นเวลา 3 นาที — 26/3/68 17:06
ตุงตุง เริ่มการโทรเป็นเวลา 18 นาที — 26/3/68 17:20
ตุงตุง เริ่มการโทรเป็นเวลา 1 ชั่วโมง — 27/3/68 15:04
มะพร้าว — 27/3/68 15:14
teacher0@gmail.com
Teacher0*
มะพร้าว — 27/3/68 15:50
<div className="bg-white p-4 rounded-lg shadow-lg w-full mx-auto overflow-y-auto border border-gray-300"
                         style={{ maxHeight: "min(80vh, 800px)" }}>
ตุงตุง เริ่มการโทรเป็นเวลา 20 นาที — 27/3/68 21:49
ตุงตุง เริ่มการโทรเป็นเวลา 2 ชั่วโมง — 27/3/68 22:40
มะพร้าว — 27/3/68 22:42
ภาพ
ภาพ
ภาพ
ภาพ
ภาพ
ภาพ
ภาพ
ตุงตุง — 28/3/68 14:42
มะพร้าวหาย
มะพร้าวไปไหน
แฟนไม่รัก
มะพร้าว — 28/3/68 14:43
รักก
ตุงตุง — 28/3/68 14:43
ไมไม่รับสาย
อยุ่ไหน
ข้างล่างหรอ
ทำไร
อึหรอ
ไมไม่รับ
อยุ่กะกิ้กหรอ
มะพร้าว — 28/3/68 14:44
พึ่งอึเสด
ตุงตุง — 28/3/68 14:44
ต้องโทรเครื่งไหน
มะพร้าว — 28/3/68 14:44
ถ้าโทรมาอันนี้ไม่เหนหน้า
ไม่มีกล้อง
ตุงตุง เริ่มการโทรเป็นเวลา 3 ชั่วโมง — 28/3/68 15:40
มะพร้าว — 28/3/68 17:38
https://github.com/Project-Mobile-Sun-Palm/project-mobile
GitHub
GitHub - Project-Mobile-Sun-Palm/project-mobile: workout application
workout application. Contribute to Project-Mobile-Sun-Palm/project-mobile development by creating an account on GitHub.
GitHub - Project-Mobile-Sun-Palm/project-mobile: workout application
มะพร้าว เริ่มการโทรเป็นเวลา 36 นาที — 28/3/68 18:59
มะพร้าว เริ่มการโทรเป็นเวลา 17 นาที — 28/3/68 22:30
ตุงตุง เริ่มการโทรเป็นเวลา 1 ชั่วโมง — เมื่อวานนี้ เวลา 00:35
ตุงตุง เริ่มการโทรเป็นเวลา 19 นาที — เมื่อวานนี้ เวลา 17:12
ตุงตุง เริ่มการโทรเป็นเวลา 25 นาที — เมื่อวานนี้ เวลา 17:33
ตุงตุง เริ่มการโทรเป็นเวลา 7 ชั่วโมง — เมื่อวานนี้ เวลา 18:51
มะพร้าว — เมื่อวานนี้ เวลา 22:14
class RoundedAppBar extends StatelessWidget implements PreferredSizeWidget {
  final String title;
  final IconData icon;
  final Widget targetPage; // 🏹 หน้าที่ต้องการไป

  const RoundedAppBar({
    Key? key,
    required this.title,
    required this.icon,
    required this.targetPage, // รับค่า targetPage
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ClipPath(
      clipper: AppBarClipper(),
      child: Container(
        color: Colors.blue,
        padding: const EdgeInsets.only(top: 30),
        child: AppBar(
          backgroundColor: Colors.transparent,
          elevation: 0,
          centerTitle: true,
          title: Text(
            title,
            style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
          ),
          actions: [
            IconButton(
              icon: Icon(icon, size: 28),
              onPressed: () {
                // 🚀 เมื่อกด Icon ให้ไปยังหน้า targetPage
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => targetPage),
                );
              },
            ),
          ],
        ),
      ),
    );
  }

  @override
  Size get preferredSize => const Size.fromHeight(100);
}
ตุงตุง — เมื่อวานนี้ เวลา 23:51
import 'package:flutter/material.dart';

class CartPage extends StatefulWidget {
  const CartPage({super.key});

  @override
ขยาย
message.txt
5 KB
มะพร้าว — 01:18
image_picker: latest_version
<key>NSCameraUsageDescription</key>
<string>We need access to your camera</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>We need access to your photo library</string>
<key>NSPhotoLibraryAddUsageDescription</key>
<string>We need permission to save photos</string>
ตุงตุง — 01:23
late String _nameProduct;
  late double _price;
  late String _description;
  late String _shopLink;
  late String _imagePath;
  late String _categories;
  late String _gender;
  late String _filter;

  Product(this._nameProduct, this._price, this._description, this._shopLink, this._imagePath, this._categories, this._gender);

  Product.fromJson(Map<String, Object?> json) {
    _nameProduct = json['product name'] as String;
    _price = json['price'] as double;
    _description = json['description'] as String;
    _shopLink = json['link shop'] as String;
    _imagePath = json['product image'] as String;
    _categories = json['categories'] as String;
    _gender = json['gender'] as String;
    _filter = json['filter'] as String;
มะพร้าว — 01:32
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:image_picker/image_picker.dart';
import 'dart:io';
ขยาย
message.txt
8 KB
ตุงตุง — 01:42
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker))
ตุงตุง เริ่มการโทรเป็นเวลา 1 ชั่วโมง — 01:51
มะพร้าว เริ่มการโทรเป็นเวลา 2 ชั่วโมง — 02:42
มะพร้าว — 03:27
Future<List<Product>> fetchProducts({String? category, String? gender, String? filter}) async {
    Query query = _firestore.collection('products');

    // กรองข้อมูลตามตัวเลือก
    if (category != null && category.isNotEmpty) {
      query = query.where('categories', isEqualTo: category);
    }
    if (gender != null && gender.isNotEmpty) {
      query = query.where('gender', isEqualTo: gender);
    }
    if (filter != null && filter.isNotEmpty) {
      query = query.where('filter', isEqualTo: filter);
    }

    QuerySnapshot querySnapshot = await query.get();
    
    return querySnapshot.docs.map((doc) => Product.fromJson(doc.data() as Map<String, dynamic>)).toList();
  }
มะพร้าว — 03:35
Future<void> loadProducts() async {
    List<Product> products = await _productService.fetchProducts(
      category: _selectedCategory,
      gender: _selectedGender,
      filter: _selectedFilter,
    );
    setState(() {
      _products = products;
    });
  }
ตุงตุง — 03:49
Widget _buildProduct() {
    return StreamBuilder(
      stream: FirebaseFirestore.instance.collection('products').where('category', isEqualTo: selectedCategory).snapshots(),
      builder: (context, AsyncSnapshot<QuerySnapshot> snapshot) {
        if(snapshot.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator());
ขยาย
message.txt
3 KB
มะพร้าว — 03:56
Expanded(
            child: ListView.builder(
              itemCount: _products.length,
              itemBuilder: (context, index) {
                return ListTile(
                  leading: Image.network(_products[index]._imagePath),
                  title: Text(_products[index]._nameProduct),
                  subtitle: Text("\$${_products[index]._price.toString()}"),
                );
              },
            ),
          ),
ตุงตุง — 04:03
class CartPage extends StatefulWidget {
  const CartPage({super.key});

  @override
  State<CartPage> createState() => _CartPageState();
}
ขยาย
message.txt
3 KB
Product.fromJson(Map<String, Object?> json) {
    _nameProduct = json['product name'] as String;
    _price = json['price'] as double;
    _description = json['description'] as String;
    _shopLink = json['link shop'] as String;
    _imagePath = json['product image'] as String;
    _categories = json['categories'] as String;
    _gender = json['gender'] as String;
    _filter = json['filter'] as String;
  }
Exception has occurred.
_TypeError (type 'Null' is not a subtype of type 'String' in type cast)
มะพร้าว — 04:11
  Product.fromJson(Map<String, dynamic> json) {
    _nameProduct = json['product name']?.toString() ?? 'Unknown';
    _price = (json['price'] as num?)?.toDouble() ?? 0.0;
    _description = json['description']?.toString() ?? 'No description';
    _shopLink = json['link shop']?.toString() ?? '';
    _imagePath = json['product image']?.toString() ?? '';
    _categories = json['categories']?.toString() ?? '';
    _gender = json['gender']?.toString() ?? '';
    _filter = json['filter']?.toString() ?? '';
  }
มะพร้าว — 14:14
Atdelthensis
Zharut
มะพร้าว — 20:56
name: NisitComSci dockerhub

on:
  push:
    branches: [main]
  pull_request:
ขยาย
dockerhub.yaml
6 KB
name: NisitComSci CI

on:
  push:
    branches: [main, develop]
  pull_request:
ขยาย
workflow.yaml
3 KB
﻿
🦋
มะพร้าว
rodan0808
 
 
name: NisitComSci dockerhub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install backend dependencies
        run: bun install
        working-directory: cs472-back

      - name: Set up Environment for backend
        run: |
          URL="${{secrets.DATABASE_URL}}"
          echo "DATABASE_URL=$URL" >> cs472-back/.env

      - name: Initialize database
        run: bunx prisma db pull
        working-directory: cs472-back

      - name: Generate Prisma Client
        run: bunx prisma generate
        working-directory: cs472-back

      - name: Run the backend tests
        run: bun test
        working-directory: cs472-back

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./cs472-back
          file: ./cs472-back/production.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nisit-comsci-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/nisit-comsci-backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/nisit-comsci-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/nisit-comsci-backend:buildcache,mode=max
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install frontend dependencies
        run: bun install
        working-directory: cs472

      - name: Set up Environment for frontend
        run: |
          BACKEND_URL="${{secrets.BACKEND_URL}}"
          AUTH_SECRET="${{secrets.AUTH_SECRET}}"
          echo "BACKEND_URL=$BACKEND_URL" >> cs472/.env
          echo "AUTH_SECRET=$AUTH_SECRET" >> cs472/.env

      - name: Run the frontend tests
        run: bun test
        working-directory: cs472

      - name: Build the frontend
        run: bun run build
        working-directory: cs472

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./cs472
          file: ./cs472/production.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nisit-comsci-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/nisit-comsci-frontend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/nisit-comsci-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/nisit-comsci-frontend:buildcache,mode=max
          build-args: |
            BACKEND_URL="${{secrets.BACKEND_URL}}"
            AUTH_SECRET="${{secrets.AUTH_SECRET}}"

  build-github-tag:
    runs-on: ubuntu-latest
    needs: [build-and-push-backend, build-and-push-frontend]
    if: github.ref == 'refs/heads/main' 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate tag
        id: generate_tag
        run: |
          NEW_TAG=$(date +'%Y.%m.%d-%H%M%S')
          echo "TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag $TAG
          git push origin $TAG
  
  build-github-release:
    runs-on: ubuntu-latest
    needs: [build-github-tag]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate release name
        id: generate_name
        run: |
          NEW_RELEASE=$(date +'%Y.%m.%d-%H%M%S')
          echo "NEW_RELEASE=$NEW_RELEASE" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ env.NEW_RELEASE }}
          release_name: Release ${{ github.ref_name }}-${{ env.NEW_RELEASE }}
          draft: false
          prerelease: false
